// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATiinsr_8wN6-v-IacMA7QFgnNMIAA1T8',
    appId: '1:233874271920:web:4bfe13bbb43eb90ca71575',
    messagingSenderId: '233874271920',
    projectId: 'threadapp-6e0bf',
    authDomain: 'threadapp-6e0bf.firebaseapp.com',
    storageBucket: 'threadapp-6e0bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRzjvyqfNj4javhc4bKndF5N6vT3PX1oc',
    appId: '1:233874271920:android:70f2b33aa547f5f4a71575',
    messagingSenderId: '233874271920',
    projectId: 'threadapp-6e0bf',
    storageBucket: 'threadapp-6e0bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMVa-zu6Bv8c8C5NTErGyTbFwXpcY4_rc',
    appId: '1:233874271920:ios:510c3aee19ab4bf3a71575',
    messagingSenderId: '233874271920',
    projectId: 'threadapp-6e0bf',
    storageBucket: 'threadapp-6e0bf.appspot.com',
    iosBundleId: 'com.example.thread',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMVa-zu6Bv8c8C5NTErGyTbFwXpcY4_rc',
    appId: '1:233874271920:ios:510c3aee19ab4bf3a71575',
    messagingSenderId: '233874271920',
    projectId: 'threadapp-6e0bf',
    storageBucket: 'threadapp-6e0bf.appspot.com',
    iosBundleId: 'com.example.thread',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATiinsr_8wN6-v-IacMA7QFgnNMIAA1T8',
    appId: '1:233874271920:web:064ed895eee05cc8a71575',
    messagingSenderId: '233874271920',
    projectId: 'threadapp-6e0bf',
    authDomain: 'threadapp-6e0bf.firebaseapp.com',
    storageBucket: 'threadapp-6e0bf.appspot.com',
  );
}
